name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          echo "Running npm ci..."
          npm ci
          echo "npm ci completed."
        working-directory: backend

      - name: List files
        run: ls -lR
        working-directory: backend

      - name: Run server
        run: node server.js
        working-directory: backend
